import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, {useEffect, useState} from "react";
import {useAccount} from "wagmi";
import Link from 'next/link'
import Header from "@/components/header/Header";

export default function Home() {

    const {isConnected} = useAccount();

    // It's a workaround,
    // details - https://ethereum.stackexchange.com/questions/133612/error-hydration-failed-because-the-initial-ui-does-not-match-what-was-rendered
    const [isDefinitelyConnected, setIsDefinitelyConnected] = useState(false);
    useEffect(() => {
        if (isConnected) {
            setIsDefinitelyConnected(true);
        } else {
            setIsDefinitelyConnected(false);
        }
    }, [isConnected]);

    return (
        <>
            <Head>
                {/* TODO fix it*/}
                <title>Community</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Header profileOwner={undefined} saveCallback={undefined} edited={false} setEdited={undefined}/>

                <div className={styles.center}>
                    {
                        isDefinitelyConnected ?
                            <Link href={"/profile/1"}>To profile</Link> :
                            <h2>Please connect wallet</h2>
                    }
                </div>
            </main>
        </>
    )
}
